### ISSUE TITLE
Implements basic endpoints.

### ISSUE THREAD

**Issue by Rumpelshtinskiy** [reductstore/reduct-java#1]
Need to create Client with follow url endpoints:
GET /info
POST /b/my_data
POST /b/my_data/{blobName}
GET /b/my_data/{blobName}?ts=timeStampValue
All endpoints should implement according to the Readme https://github.com/reduct-storage/reduct-storage#reduct-storage
Who to ask questions about the task: https://github.com/flipback

**Comment by flipback** [comment]
Hey @Rumpelshtinskiy , it is better to use the documentation of APIs:
https://docs.reduct-storage.dev - stable v0.1.1 version
https://docsdev.reduct-storage.dev - dev v0.2.0 version.

**Comment by atimin** [comment]
@matepocz took over the project and is working according to his plan.
