### ISSUE TITLE
Feature: Improve ReductClient initialization

### ISSUE THREAD

**Issue by atimin** [reductstore/reduct-java#41]
### Current problem

Client initialization is verbose and counter-intuitive: 

```java
        ServerProperties properties = new ServerProperties(false, "127.0.0.1", 8383);
        HttpClient httpClient = HttpClient.newHttpClient();
        ReductClient client = new ReductClient(properties, httpClient, "my-token");
```

### Possible solution

Let's pass the URL and token to `ServerProperties` and use the builder pattern because in the future we will need timeout and other options:

```java
        ServerProperties properties = ServerProperties
            .url(:http://127.0.0.1:8383)
            .apiToken("my-token");

        HttpClient httpClient = HttpClient.newHttpClient();
        ReductClient client = new ReductClient(properties, httpClient);
```

Additionally, lets add a constructor with a default HTTP client. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rumpelshtinskiy** [comment]
I've started to work on the issue
