### ISSUE TITLE
Bug: Bucket.query handle only one HTTP GET request

### ISSUE THREAD

**Issue by atimin** [reductstore/reduct-java#47]
### What happened?

The method receives the `queryId' but retrieves data for it only once. It must repeat the GET requests until it receives HTTP status 204.

### Version

0.1.0

### OS

Linux, MacOS, Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rumpelshtinskiy** [comment]
I've started to work on the issue
